# Generated by Django 5.1.1 on 2024-09-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelToDb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='upload_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
