# Generated by Django 5.1.1 on 2024-09-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelToDb', '0002_alter_transaction_upload_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receive_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
